import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import WebSocket, { WebSocketServer } from 'ws';
import { once } from 'node:events';
import { createHost } from '../src/server.mjs';
import { Workspace } from '../src/workspace.mjs';
import { ProjectHistory } from '../src/project-history.mjs';
import { Transfers } from '../src/transfers.mjs';
import { digest } from '../src/session.mjs';

async function setup(t){
  const dir=await mkdtemp(path.join(os.tmpdir(),'hih-project-')),root=path.join(dir,'project'),dataDir=path.join(dir,'state');
  await mkdir(root);await writeFile(path.join(root,'index.html'),'<html><body>first</body></html>');
  const host=await createHost({port:0,dataDir,workspace:root,allowLocalAgent:false});
  t.after(async()=>{await host.close();await rm(dir,{recursive:true,force:true});});
  const call=async(route,p,token)=>{const response=await fetch(host.url+route,{method:p===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:p===undefined?undefined:JSON.stringify(p)});return {status:response.status,data:await response.json()};};
  const owner=(await call('/api/bootstrap',{})).data;
  const member=async role=>{const invite=(await call('/api/invites',{role},owner.token)).data;return (await call('/api/join',{code:invite.code,name:role})).data;};
  return {host,root,dataDir,call,owner,member};
}
test('observer can view and export but cannot pair, submit, upload or manage preview',async t=>{
  const {host,call,owner,member}=await setup(t),observer=await member('observer');
  assert.equal(observer.member.role,'observer');
  assert.equal((await call('/api/state',undefined,observer.token)).status,200);
  for(const route of ['/api/pairing','/api/turns','/api/uploads','/api/preview/config','/api/invites'])assert.equal((await call(route,{},observer.token)).status,403,route);
  const exported=(await call('/api/session/export',undefined,observer.token)).data;
  assert.equal(exported.id,host.store.state.id);assert.ok(!JSON.stringify(exported).includes('tokenHash'));
  await call(`/api/members/${observer.member.id}/revoke`,{},owner.token);
  assert.equal((await call('/api/session/export',undefined,observer.token)).status,401);
});
test('durable upload resumes after reconnect, verifies hash, refuses wrong author and never overwrites',async t=>{
  const {call,owner,member,root,dataDir}=await setup(t),b=await member('member'),bytes=Buffer.from('첫 조각과 두 번째 조각'),hash=digest(bytes);
  const info=(await call('/api/uploads',{name:'assets/data.txt',size:bytes.length,hash},b.token)).data;
  const piece={offset:0,data:bytes.subarray(0,6).toString('base64')};
  assert.equal((await call(`/api/uploads/${info.id}/chunk`,piece,owner.token)).status,400);
  assert.equal((await call(`/api/uploads/${info.id}/chunk`,piece,b.token)).data.offset,6);
  assert.equal((await call(`/api/uploads/${info.id}/chunk`,piece,b.token)).data.offset,6);
  const transfers=new Transfers(new Workspace(root),dataDir);assert.equal((await transfers.get(info.id,b.member.id)).offset,6);
  await transfers.chunk(info.id,b.member.id,{offset:6,data:bytes.subarray(6).toString('base64')});
  assert.equal((await call(`/api/uploads/${info.id}/complete`,{},b.token)).status,200);
  assert.equal((await call(`/api/uploads/${info.id}/complete`,{},b.token)).status,200);
  assert.deepEqual(await readFile(path.join(root,'assets/data.txt')),bytes);
  const collision=await transfers.start(b.member.id,{name:'assets/data.txt',size:0,hash:digest('')});
  await assert.rejects(transfers.finish(collision.id,b.member.id),/동일 이름/);
  await assert.rejects(transfers.start(b.member.id,{name:'.env',size:0,hash:digest('')}));
  const bad=await transfers.start(b.member.id,{name:'wrong.txt',size:1,hash:digest('x')});await transfers.chunk(bad.id,b.member.id,{offset:0,data:Buffer.from('y').toString('base64')});await assert.rejects(transfers.finish(bad.id,b.member.id),/검증/);
  const events=(await call('/api/state',undefined,owner.token)).data.fileEvents;assert.equal(events.length,1);
});
test('file backups include additions and deletions; recovery refuses later edits and preserves native history',async t=>{
  const {root,dataDir,host}=await setup(t),history=new ProjectHistory(new Workspace(root),dataDir),id=randomUUID();
  const checkpoint=host.store.state.checkpoint;
  await writeFile(path.join(root,'remove.txt'),'recover me');await history.begin(id);
  await writeFile(path.join(root,'index.html'),'changed');await writeFile(path.join(root,'new.txt'),'new file');await rm(path.join(root,'remove.txt'));
  const record=await history.finish(id);assert.equal(record.changes.length,3);
  assert.equal((await history.detail(id)).changes.find(c=>c.path==='index.html').afterView.content,'changed');
  await writeFile(path.join(root,'index.html'),'a later edit');await assert.rejects(history.restore(id,'index.html','owner'),/충돌/);
  await history.restore(id,'remove.txt','owner');assert.equal(await readFile(path.join(root,'remove.txt'),'utf8'),'recover me');
  await history.restore(id,'new.txt','owner');await assert.rejects(readFile(path.join(root,'new.txt')),/ENOENT/);
  assert.equal(host.store.state.checkpoint,checkpoint);
});
test('host captures native writes and prevents upload commits and new sessions during an active turn',async t=>{
  const {call,owner,root,host}=await setup(t);
  const code=(await call('/api/pairing',{},owner.token)).data.code,agent=(await call('/api/agent/pair',{code})).data;
  await call('/api/worker/register',{runnerId:'r',protocolVersion:3,account:'owner'},agent.token);
  const queued=(await call('/api/turns',{prompt:'edit the file',requestId:'r1'},owner.token)).data.turn;
  assert.equal((await call('/api/session/new',{title:'lose queued'},owner.token)).status,400);
  const {job}=(await call('/api/worker/claim',{runnerId:'r'},agent.token)).data;
  const info=(await call('/api/uploads',{name:'new.txt',size:0,hash:digest('')},owner.token)).data;
  assert.equal((await call(`/api/uploads/${info.id}/complete`,{},owner.token)).status,400);
  await writeFile(path.join(root,'index.html'),'native shell changed this');
  const nativeId=randomUUID(),checkpoint=[{type:'session_meta',payload:{id:nativeId}},{type:'response_item',payload:{type:'message',role:'user',content:[{type:'input_text',text:job.prompt}]}}].map(r=>JSON.stringify(r)+'\n').join('');
  const result=await call(`/api/worker/turns/${job.id}/complete`,{lease:job.lease,nativeId,checkpoint,status:'completed'},agent.token);assert.equal(result.status,200);
  const changes=(await call(`/api/changes/${queued.id}`,undefined,owner.token)).data;assert.equal(changes.changes[0].path,'index.html');
  await call(`/api/changes/${queued.id}/restore`,{path:'index.html'},owner.token);
  assert.equal(await readFile(path.join(root,'index.html'),'utf8'),'<html><body>first</body></html>');assert.equal(host.store.state.checkpoint,checkpoint);
  await call('/api/turns',{prompt:'Continue after the restoration',requestId:'r2'},owner.token);
  const next=(await call('/api/worker/claim',{runnerId:'r'},agent.token)).data.job;
  assert.match(next.prompt,/restore/);assert.match(next.prompt,/index.html/);assert.match(next.prompt,/Continue after the restoration/);
  assert.equal(next.checkpoint,checkpoint);assert.equal(next.nativeId,nativeId);
  const missing=checkpoint+JSON.stringify({type:'response_item',payload:{type:'message',role:'user',content:[{text:'Continue after the restoration'}]}})+'\n';
  assert.equal((await call(`/api/worker/turns/${next.id}/complete`,{lease:next.lease,nativeId,checkpoint:missing,status:'completed'},agent.token)).status,400);
  assert.equal(host.store.state.checkpoint,checkpoint);
  const complete=checkpoint+JSON.stringify({type:'response_item',payload:{type:'message',role:'user',content:[{text:next.prompt}]}})+'\n';
  assert.equal((await call(`/api/worker/turns/${next.id}/complete`,{lease:next.lease,nativeId,checkpoint:complete,status:'completed'},agent.token)).status,200);
});
test('archived sessions are owner-only, exclude credentials, and keep the current conversation intact',async t=>{
  const {call,owner,member,host}=await setup(t),b=await member('member'),old=host.store.state.id;
  assert.equal((await call('/api/session/new',{title:'Next'},owner.token)).status,200);
  const current=host.store.state.id;assert.notEqual(current,old);
  const archives=(await call('/api/session/archives',undefined,owner.token)).data.archives;assert.equal(archives[0].id,old);
  const saved=(await call('/api/session/archives/'+old,undefined,owner.token)).data;
  assert.ok(!JSON.stringify(saved).includes('tokenHash'));assert.equal(saved.id,old);assert.equal(host.store.state.id,current);
  assert.equal((await call('/api/session/archives/'+old,undefined,b.token)).status,403);
});
test('preview uses an isolated authenticated origin, strips secrets and forwards relative assets and WebSocket',async t=>{
  const {host,call,owner,member}=await setup(t),b=await member('observer');
  const requests=[];
  const dev=http.createServer((req,res)=>{requests.push({url:req.url,headers:req.headers});res.setHeader('Set-Cookie','project=must-not-forward');res.end(req.url==='/asset.js'?'export const live = true;':'<html><script src="/asset.js"></script></html>');});
  await new Promise(resolve=>dev.listen(0,'127.0.0.1',resolve));
  const wss=new WebSocketServer({server:dev});wss.on('connection',ws=>ws.on('message',message=>ws.send(message)));
  t.after(async()=>{for(const ws of wss.clients)ws.terminate();wss.close();dev.closeAllConnections();await new Promise(resolve=>dev.close(resolve));});
  assert.equal((await call('/api/preview/config',{port:host.port},owner.token)).status,400);
  const config=(await call('/api/preview/config',{port:dev.address().port},owner.token)).data;assert.notEqual(config.localUrl,host.url);
  assert.equal((await fetch(config.localUrl)).status,403);
  const ticket=(await call('/api/preview/open',{},b.token)).data;
  const opened=await fetch(ticket.url,{redirect:'manual'});assert.equal(opened.status,303);
  const cookie=opened.headers.get('set-cookie').split(';')[0];assert.match(opened.headers.get('set-cookie'),/HttpOnly/);
  assert.equal((await fetch(ticket.url,{redirect:'manual'})).status,403);
  const response=await fetch(config.localUrl+'/asset.js',{headers:{Cookie:cookie,Authorization:'Bearer must-not-forward'}});
  assert.equal(await response.text(),'export const live = true;');assert.equal(response.headers.get('set-cookie'),null);
  assert.equal(requests.at(-1).headers.authorization,undefined);assert.equal(requests.at(-1).headers.cookie,undefined);
  assert.match(response.headers.get('content-security-policy'),/frame-ancestors/);
  assert.equal((await fetch(config.localUrl,{headers:{Cookie:cookie,Origin:host.url}})).status,403);
  const ws=new WebSocket(config.localUrl.replace('http:','ws:')+'/live',{headers:{Cookie:cookie,Origin:config.localUrl}});
  await once(ws,'open');ws.send('reload');const [echo]=await once(ws,'message');assert.equal(echo.toString(),'reload');
  const ended=once(ws,'close');await call(`/api/members/${b.member.id}/revoke`,{},owner.token);await ended;
  assert.equal((await fetch(config.localUrl,{headers:{Cookie:cookie}})).status,403);
});
test('authenticated downloads preserve binary bytes and exclude secrets and path escapes',async t=>{
  const {host,root,call,owner}=await setup(t);const bytes=Buffer.from([0,255,3,4]);await writeFile(path.join(root,'artifact.bin'),bytes);
  const response=await fetch(host.url+'/api/download?path=artifact.bin',{headers:{Authorization:`Bearer ${owner.token}`}});
  assert.deepEqual(Buffer.from(await response.arrayBuffer()),bytes);
  assert.match(response.headers.get('content-disposition'),/attachment/);
  for(const name of ['.env','../private','C:/private'])assert.equal((await call('/api/download?path='+encodeURIComponent(name),undefined,owner.token)).status,400);
});
